---
- name: Add Jobs
  jenkins_job:
    config: "{{ lookup('file', '{{ item }}/config.xml') }}"
    name: "{{ item }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}"
    user: admin
  with_items: "{{ jenkins_jobs }}"
  tags:
    - jobs
