---
# Prerequisite stuff for Jenkins
- name: ensure that epel is available
  yum:
    name: http://mirror.ufs.ac.za/fedora-epel/epel-release-latest-7.noarch.rpm
    state: present
    update_cache: true

- name: ensure that the jenkins repo is available
  get_url:
    url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    owner: root
    group: root

- name: ensure that the Jenkins RPM key is available
  rpm_key:
    key: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    state: present

- name: update yum cache
  yum:
    name: '*'
    state: latest
    update_cache: true
  changed_when: false

- name: ensure prerequisites are present
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ jenkins_prerequisites }}"

- name: install openjdk
  yum:
    name: "{{ openjdk_package }}"
    state: present
