---
- name: install jenkins
  yum:
    name: jenkins
    state: present

- name: ensure that jenkins is running
  service:
    name: jenkins
    state: started

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    connect_timeout: 5
    host: "{{ jenkins_hostname }}"
    port: "{{ jenkins_http_port }}"

- name: debug
  debug:
    var: "{{ item}}"
  with_items:
    - jenkins_admin_username
    - jenkins_admin_password

- name: Ensure that CLI is available
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli"
    return_content: yes
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
  register: result
  # until: (result.response.find("403 Forbidden") != -1) or (result.response.find("200 OK") != -1) and (result.response.find("Please wait while") == -1)
  # retries: "{{ jenkins_connection_retries }}"
  ignore_errors: true

- name: debug
  debug:
    var: result.status
