---
- name: install jenkins
  yum:
    name: jenkins
    state: present

- name: Add Jenkins user to docker group
  user:
    name: jenkins
    groups:
      - docker
      - jenkins


- name: Ensure that the wizard doesn't run
  replace:
    dest: /etc/sysconfig/jenkins
    regexp: "^JENKINS_JAVA_OPTIONS=.*$"
    replace: "JENKINS_JAVA_OPTIONS='{{ jenkins_java_options }}'"


- name: ensure that jenkins is running
  service:
    name: jenkins
    state: started

- name: Wait for Jenkins to start up before proceeding.
  wait_for:
    connect_timeout: 5
    host: "{{ jenkins_hostname }}"
    port: "{{ jenkins_http_port }}"

- name: Look for temporary password
  shell: grep -A2  password /var/log/jenkins/jenkins.log |tail -n1
  register: new_password

- name: debug
  debug:
    var: "{{ item}}"
  with_items:
    - new_password
    - jenkins_admin_username
    - jenkins_admin_password

- name: Ensure that CLI is available
  uri:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/cli"
    return_content: yes
    method: GET
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    force_basic_auth: yes
  register: result
  # until: (result.response.find("403 Forbidden") != -1) or (result.response.find("200 OK") != -1) and (result.response.find("Please wait while") == -1)
  # retries: "{{ jenkins_connection_retries }}"
  ignore_errors: true

- name: debug
  debug:
    var: result.status
