---
# handlers file for jenkins-server
- name: restart jenkins
  uri:
    method: POST
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password_file }}"
    force_basic_auth: true
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}/safeRestart"

- name: restart jenkins service
  become: true
  service:
    name: jenkins
    state: restarted
